Class CTPlayerReplicationInfo extends KFPlayerReplicationInfo;

// For custom trader inventory.
struct FCustomTraderItem
{
	var class<KFWeaponDefinition> WeaponDef;
	var class<KFWeapon> WeaponClass;
};

var transient CTPlayerReplicationInfo LocalOwnerPRI; // Local playercontroller owner PRI

// Custom trader inventory
var KFGFxObject_TraderItems CustomList;
var array<FCustomTraderItem> CustomItems;
var KFGFxObject_TraderItems MyTraderItems;

simulated function PostBeginPlay()
{
	Super.PostBeginPlay();
	SetTimer(1.0, true, 'UpdateTI');
}

simulated function UpdateTI()
{
	KFGameReplicationInfo(WorldInfo.GRI).TraderItems=MyTraderItems;	
}

defaultproperties
{
	
Begin Object Class=KFGFxObject_TraderItems Name=MyDefaultTraderItems
   SaleItems(0)=(WeaponDef=Class'KFGame.KFWeapDef_Crovel',ClassName="KFWeap_Blunt_Crovel",AssociatedPerkClasses=(Class'KFGame.KFPerk_Berserker'),SecondaryAmmoImagePath="UI_SecondaryAmmo_TEX.GasTank",GroupPriority=25.000000,WeaponStats=((StatValue=86.000000),(StatType=TWS_Penetration),(StatType=TWS_Range,StatValue=3.000000),(StatType=TWS_RateOfFire,StatValue=100.000000),(StatType=TWS_Block,StatValue=0.600000),(StatType=TWS_Parry,StatValue=0.500000)),BlocksRequired=4,TraderFilter=FT_Melee,InventoryGroup=2,ItemId=0)
   SaleItems(1)=(WeaponDef=Class'KFGame.KFWeapDef_Katana',ClassName="KFWeap_Edged_Katana",AssociatedPerkClasses=(Class'KFGame.KFPerk_Berserker'),SecondaryAmmoImagePath="UI_SecondaryAmmo_TEX.GasTank",GroupPriority=100.000000,WeaponStats=((StatValue=90.000000),(StatType=TWS_Penetration),(StatType=TWS_Range,StatValue=2.000000),(StatType=TWS_RateOfFire,StatValue=100.000000),(StatType=TWS_Block,StatValue=0.600000),(StatType=TWS_Parry,StatValue=0.500000)),BlocksRequired=3,TraderFilter=FT_Melee,InventoryGroup=2,ItemId=1)
   SaleItems(2)=(WeaponDef=Class'KFGame.KFWeapDef_Nailgun',ClassName="KFWeap_Shotgun_Nailgun",AssociatedPerkClasses=(Class'KFGame.KFPerk_Berserker',Class'KFGame.KFPerk_Support'),MaxSpareAmmo=336,SecondaryAmmoImagePath="UI_SecondaryAmmo_TEX.GasTank",GroupPriority=50.000000,WeaponStats=((StatValue=210.000000),(StatType=TWS_Penetration,StatValue=2.000000),(StatType=TWS_Range,StatValue=20.000000),(StatType=TWS_RateOfFire,StatValue=150.000000)),InitialSpareMags=4,MagazineCapacity=42,BlocksRequired=6,TraderFilter=FT_Shotgun,ItemId=2)
   SaleItems(3)=(WeaponDef=Class'KFGame.KFWeapDef_Zweihander',ClassName="KFWeap_Edged_Zweihander",AssociatedPerkClasses=(Class'KFGame.KFPerk_Berserker'),SecondaryAmmoImagePath="UI_SecondaryAmmo_TEX.GasTank",GroupPriority=85.000000,WeaponStats=((StatValue=195.000000),(StatType=TWS_Penetration),(StatType=TWS_Range,StatValue=3.000000),(StatType=TWS_RateOfFire,StatValue=100.000000),(StatType=TWS_Block,StatValue=0.500000),(StatType=TWS_Parry,StatValue=0.400000)),BlocksRequired=6,TraderFilter=FT_Melee,InventoryGroup=2,ItemId=3)
   SaleItems(4)=(WeaponDef=Class'KFGame.KFWeapDef_Pulverizer',ClassName="KFWeap_Blunt_Pulverizer",AssociatedPerkClasses=(Class'KFGame.KFPerk_Berserker',Class'KFGame.KFPerk_Demolitionist'),MaxSpareAmmo=15,SecondaryAmmoImagePath="UI_SecondaryAmmo_TEX.GasTank",GroupPriority=75.000000,WeaponStats=((StatValue=145.000000),(StatType=TWS_Penetration),(StatType=TWS_Range,StatValue=3.000000),(StatType=TWS_RateOfFire,StatValue=100.000000),(StatType=TWS_Block,StatValue=0.500000),(StatType=TWS_Parry,StatValue=0.400000)),MagazineCapacity=5,BlocksRequired=6,TraderFilter=FT_Melee,InventoryGroup=2,ItemId=4)
   SaleItems(5)=(WeaponDef=Class'KFGame.KFWeapDef_Eviscerator',ClassName="KFWeap_Eviscerator",AssociatedPerkClasses=(Class'KFGame.KFPerk_Berserker'),MaxSpareAmmo=25,SecondaryAmmoImagePath="UI_SecondaryAmmo_TEX.GasTank",GroupPriority=100.000000,WeaponStats=((StatValue=480.000000),(StatType=TWS_Penetration,StatValue=4.000000),(StatType=TWS_Range,StatValue=25.000000),(StatType=TWS_RateOfFire,StatValue=100.000000),(StatType=TWS_Block,StatValue=0.400000),(StatType=TWS_Parry,StatValue=0.300000)),MagazineCapacity=5,BlocksRequired=10,InitialSecondaryAmmo=250,MaxSecondaryAmmo=250,TraderFilter=FT_Projectile,AltTraderFilter=FT_Melee,ItemId=5)
   SaleItems(6)=(WeaponDef=Class'KFGame.KFWeapDef_MaceAndShield',ClassName="KFWeap_Blunt_MaceAndShield",AssociatedPerkClasses=(Class'KFGame.KFPerk_Berserker'),SecondaryAmmoImagePath="UI_SecondaryAmmo_TEX.GasTank",GroupPriority=110.000000,WeaponStats=((StatValue=165.000000),(StatType=TWS_Penetration),(StatType=TWS_Range,StatValue=3.000000),(StatType=TWS_RateOfFire,StatValue=100.000000),(StatType=TWS_Block,StatValue=0.300000),(StatType=TWS_Parry,StatValue=0.400000)),BlocksRequired=9,TraderFilter=FT_Melee,InventoryGroup=2,ItemId=6)
   SaleItems(7)=(WeaponDef=Class'KFGame.KFWeapDef_AR15',ClassName="KFWeap_AssaultRifle_AR15",AssociatedPerkClasses=(Class'KFGame.KFPerk_Commando'),MaxSpareAmmo=240,SecondaryAmmoImagePath="UI_SecondaryAmmo_TEX.GasTank",GroupPriority=25.000000,WeaponStats=((StatValue=30.000000),(StatType=TWS_Penetration),(StatType=TWS_Range,StatValue=60.000000),(StatType=TWS_RateOfFire,StatValue=500.000000)),InitialSpareMags=6,MagazineCapacity=20,BlocksRequired=4,TraderFilter=FT_Assault,ItemId=7)
   SaleItems(8)=(WeaponDef=Class'KFGame.KFWeapDef_Bullpup',ClassName="KFWeap_AssaultRifle_Bullpup",AssociatedPerkClasses=(Class'KFGame.KFPerk_Commando'),MaxSpareAmmo=270,SecondaryAmmoImagePath="UI_SecondaryAmmo_TEX.GasTank",GroupPriority=50.000000,WeaponStats=((StatValue=30.000000),(StatType=TWS_Penetration),(StatType=TWS_Range,StatValue=68.000000),(StatType=TWS_RateOfFire,StatValue=660.066040)),InitialSpareMags=4,MagazineCapacity=30,BlocksRequired=6,TraderFilter=FT_Assault,ItemId=8)
   SaleItems(9)=(WeaponDef=Class'KFGame.KFWeapDef_AK12',ClassName="KFWeap_AssaultRifle_AK12",AssociatedPerkClasses=(Class'KFGame.KFPerk_Commando'),MaxSpareAmmo=300,SecondaryAmmoImagePath="UI_SecondaryAmmo_TEX.GasTank",GroupPriority=75.000000,WeaponStats=((StatValue=40.000000),(StatType=TWS_Penetration),(StatType=TWS_Range,StatValue=67.000000),(StatType=TWS_RateOfFire,StatValue=600.000000)),InitialSpareMags=3,MagazineCapacity=30,BlocksRequired=6,TraderFilter=FT_Assault,ItemId=9)
   SaleItems(10)=(WeaponDef=Class'KFGame.KFWeapDef_SCAR',ClassName="KFWeap_AssaultRifle_SCAR",AssociatedPerkClasses=(Class'KFGame.KFPerk_Commando'),MaxSpareAmmo=340,SecondaryAmmoImagePath="UI_SecondaryAmmo_TEX.GasTank",GroupPriority=100.000000,WeaponStats=((StatValue=55.000000),(StatType=TWS_Penetration),(StatType=TWS_Range,StatValue=70.000000),(StatType=TWS_RateOfFire,StatValue=625.000000)),InitialSpareMags=4,MagazineCapacity=20,BlocksRequired=6,TraderFilter=FT_Assault,ItemId=10)
   SaleItems(11)=(WeaponDef=Class'KFGame.KFWeapDef_Stoner63A',ClassName="KFWeap_LMG_Stoner63A",AssociatedPerkClasses=(Class'KFGame.KFPerk_Commando'),MaxSpareAmmo=500,SecondaryAmmoImagePath="UI_SecondaryAmmo_TEX.GasTank",GroupPriority=100.000000,WeaponStats=((StatValue=30.000000),(StatType=TWS_Penetration),(StatType=TWS_Range,StatValue=68.000000),(StatType=TWS_RateOfFire,StatValue=909.090942)),InitialSpareMags=1,MagazineCapacity=75,BlocksRequired=9,TraderFilter=FT_Assault,ItemId=11)
   SaleItems(12)=(WeaponDef=Class'KFGame.KFWeapDef_HX25',ClassName="KFWeap_GrenadeLauncher_HX25",AssociatedPerkClasses=(Class'KFGame.KFPerk_Demolitionist',Class'KFGame.KFPerk_Gunslinger'),MaxSpareAmmo=29,SecondaryAmmoImagePath="UI_SecondaryAmmo_TEX.GasTank",GroupPriority=25.000000,WeaponStats=((StatValue=280.000000),(StatType=TWS_Penetration),(StatType=TWS_Range,StatValue=25.000000),(StatType=TWS_RateOfFire,StatValue=240.000000)),InitialSpareMags=17,MagazineCapacity=1,BlocksRequired=4,TraderFilter=FT_Explosive,AltTraderFilter=FT_Pistol,InventoryGroup=1,ItemId=12)
   SaleItems(13)=(WeaponDef=Class'KFGame.KFWeapDef_C4',ClassName="KFWeap_Thrown_C4",AssociatedPerkClasses=(Class'KFGame.KFPerk_Demolitionist'),MaxSpareAmmo=1,SecondaryAmmoImagePath="UI_SecondaryAmmo_TEX.GasTank",GroupPriority=50.000000,WeaponStats=((StatValue=820.000000),(StatType=TWS_Penetration),(StatType=TWS_Range,StatValue=10.000000),(StatType=TWS_RateOfFire,StatValue=240.000000)),InitialSpareMags=1,MagazineCapacity=1,BlocksRequired=3,TraderFilter=FT_Explosive,ItemId=13)
   SaleItems(14)=(WeaponDef=Class'KFGame.KFWeapDef_M79',ClassName="KFWeap_GrenadeLauncher_M79",AssociatedPerkClasses=(Class'KFGame.KFPerk_Demolitionist'),MaxSpareAmmo=26,SecondaryAmmoImagePath="UI_SecondaryAmmo_TEX.GasTank",GroupPriority=75.000000,WeaponStats=((StatValue=375.000000),(StatType=TWS_Penetration),(StatType=TWS_Range,StatValue=100.000000),(StatType=TWS_RateOfFire,StatValue=240.000000)),InitialSpareMags=9,MagazineCapacity=1,BlocksRequired=6,TraderFilter=FT_Explosive,ItemId=14)
   SaleItems(15)=(WeaponDef=Class'KFGame.KFWeapDef_RPG7',ClassName="KFWeap_RocketLauncher_RPG7",AssociatedPerkClasses=(Class'KFGame.KFPerk_Demolitionist'),MaxSpareAmmo=15,SecondaryAmmoImagePath="UI_SecondaryAmmo_TEX.GasTank",GroupPriority=100.000000,WeaponStats=((StatValue=900.000000),(StatType=TWS_Penetration),(StatType=TWS_Range,StatValue=100.000000),(StatType=TWS_RateOfFire,StatValue=240.000000)),InitialSpareMags=4,MagazineCapacity=1,BlocksRequired=9,TraderFilter=FT_Explosive,ItemId=15)
   SaleItems(16)=(WeaponDef=Class'KFGame.KFWeapDef_Seeker6',ClassName="KFWeap_RocketLauncher_Seeker6",AssociatedPerkClasses=(Class'KFGame.KFPerk_Demolitionist'),MaxSpareAmmo=84,SecondaryAmmoImagePath="UI_SecondaryAmmo_TEX.GasTank",GroupPriority=100.000000,WeaponStats=((StatValue=225.000000),(StatType=TWS_Penetration),(StatType=TWS_Range,StatValue=100.000000),(StatType=TWS_RateOfFire,StatValue=171.428574)),InitialSpareMags=3,MagazineCapacity=6,BlocksRequired=9,TraderFilter=FT_Explosive,ItemId=16)
   SaleItems(17)=(WeaponDef=Class'KFGame.KFWeapDef_MedicPistol',ClassName="KFWeap_Pistol_Medic",AssociatedPerkClasses=(Class'KFGame.KFPerk_FieldMedic',Class'KFGame.KFPerk_Gunslinger'),MaxSpareAmmo=240,SecondaryAmmoImagePath="UI_SecondaryAmmo_TEX.MedicDarts",GroupPriority=25.000000,WeaponStats=((StatValue=20.000000),(StatType=TWS_Penetration),(StatType=TWS_Range,StatValue=50.000000),(StatType=TWS_RateOfFire,StatValue=342.857147),(StatType=TWS_HealAmount,StatValue=15.000000),(StatType=TWS_RechargeTime,StatValue=15.000000)),InitialSpareMags=8,MagazineCapacity=15,BlocksRequired=1,InitialSecondaryAmmo=100,MaxSecondaryAmmo=100,InventoryGroup=1,ItemId=17)
   SaleItems(18)=(WeaponDef=Class'KFGame.KFWeapDef_MedicSMG',ClassName="KFWeap_SMG_Medic",AssociatedPerkClasses=(Class'KFGame.KFPerk_FieldMedic',Class'KFGame.KFPerk_SWAT'),MaxSpareAmmo=480,SecondaryAmmoImagePath="UI_SecondaryAmmo_TEX.MedicDarts",GroupPriority=50.000000,WeaponStats=((StatValue=15.000000),(StatType=TWS_Penetration),(StatType=TWS_Range,StatValue=70.000000),(StatType=TWS_RateOfFire,StatValue=799.999939),(StatType=TWS_HealAmount,StatValue=15.000000),(StatType=TWS_RechargeTime,StatValue=15.000000)),InitialSpareMags=5,MagazineCapacity=40,BlocksRequired=3,InitialSecondaryAmmo=100,MaxSecondaryAmmo=100,TraderFilter=FT_SMG,ItemId=18)
   SaleItems(19)=(WeaponDef=Class'KFGame.KFWeapDef_MedicShotgun',ClassName="KFWeap_Shotgun_Medic",AssociatedPerkClasses=(Class'KFGame.KFPerk_FieldMedic',Class'KFGame.KFPerk_Support'),MaxSpareAmmo=80,SecondaryAmmoImagePath="UI_SecondaryAmmo_TEX.MedicDarts",GroupPriority=75.000000,WeaponStats=((StatValue=120.000000),(StatType=TWS_Penetration,StatValue=2.000000),(StatType=TWS_Range,StatValue=50.000000),(StatType=TWS_RateOfFire,StatValue=300.000000),(StatType=TWS_HealAmount,StatValue=15.000000),(StatType=TWS_RechargeTime,StatValue=12.000000)),InitialSpareMags=3,MagazineCapacity=10,BlocksRequired=6,InitialSecondaryAmmo=100,MaxSecondaryAmmo=100,TraderFilter=FT_Shotgun,ItemId=19)
   SaleItems(20)=(WeaponDef=Class'KFGame.KFWeapDef_MedicRifle',ClassName="KFWeap_AssaultRifle_Medic",AssociatedPerkClasses=(Class'KFGame.KFPerk_FieldMedic',Class'KFGame.KFPerk_Commando'),MaxSpareAmmo=400,SecondaryAmmoImagePath="UI_SecondaryAmmo_TEX.MedicDarts",GroupPriority=100.000000,WeaponStats=((StatValue=35.000000),(StatType=TWS_Penetration),(StatType=TWS_Range,StatValue=70.000000),(StatType=TWS_RateOfFire,StatValue=750.000000),(StatType=TWS_HealAmount,StatValue=15.000000),(StatType=TWS_RechargeTime,StatValue=10.000000)),InitialSpareMags=2,MagazineCapacity=40,BlocksRequired=7,InitialSecondaryAmmo=100,MaxSecondaryAmmo=100,TraderFilter=FT_Assault,ItemId=20)
   SaleItems(21)=(WeaponDef=Class'KFGame.KFWeapDef_Remington1858',ClassName="KFWeap_Revolver_Rem1858",DualClassName="KFWeap_Revolver_DualRem1858",AssociatedPerkClasses=(Class'KFGame.KFPerk_Gunslinger',Class'KFGame.KFPerk_Sharpshooter'),MaxSpareAmmo=186,SecondaryAmmoImagePath="UI_SecondaryAmmo_TEX.GasTank",GroupPriority=15.000000,WeaponStats=((StatValue=30.000000),(StatType=TWS_Penetration),(StatType=TWS_Range,StatValue=50.000000),(StatType=TWS_RateOfFire,StatValue=300.000000)),InitialSpareMags=15,MagazineCapacity=6,BlocksRequired=2,InventoryGroup=1,ItemId=21)
   SaleItems(22)=(WeaponDef=Class'KFGame.KFWeapDef_Remington1858Dual',ClassName="KFWeap_Revolver_DualRem1858",SingleClassName="KFWeap_Revolver_Rem1858",AssociatedPerkClasses=(Class'KFGame.KFPerk_Gunslinger'),MaxSpareAmmo=180,SecondaryAmmoImagePath="UI_SecondaryAmmo_TEX.GasTank",GroupPriority=35.000000,WeaponStats=((StatValue=30.000000),(StatType=TWS_Penetration),(StatType=TWS_Range,StatValue=50.000000),(StatType=TWS_RateOfFire,StatValue=545.454529)),InitialSpareMags=7,MagazineCapacity=12,BlocksRequired=4,ItemId=22)
   SaleItems(23)=(WeaponDef=Class'KFGame.KFWeapDef_Colt1911',ClassName="KFWeap_Pistol_Colt1911",DualClassName="KFWeap_Pistol_DualColt1911",AssociatedPerkClasses=(Class'KFGame.KFPerk_Gunslinger'),MaxSpareAmmo=136,SecondaryAmmoImagePath="UI_SecondaryAmmo_TEX.GasTank",GroupPriority=20.000000,WeaponStats=((StatValue=50.000000),(StatType=TWS_Penetration,StatValue=1.000000),(StatType=TWS_Range,StatValue=50.000000),(StatType=TWS_RateOfFire,StatValue=342.857147)),InitialSpareMags=7,MagazineCapacity=8,BlocksRequired=2,InventoryGroup=1,ItemId=23)
   SaleItems(24)=(WeaponDef=Class'KFGame.KFWeapDef_Colt1911Dual',ClassName="KFWeap_Pistol_DualColt1911",SingleClassName="KFWeap_Pistol_Colt1911",AssociatedPerkClasses=(Class'KFGame.KFPerk_Gunslinger'),MaxSpareAmmo=128,SecondaryAmmoImagePath="UI_SecondaryAmmo_TEX.GasTank",GroupPriority=40.000000,WeaponStats=((StatValue=50.000000),(StatType=TWS_Penetration,StatValue=1.000000),(StatType=TWS_Range,StatValue=50.000000),(StatType=TWS_RateOfFire,StatValue=600.000000)),InitialSpareMags=3,MagazineCapacity=16,BlocksRequired=4,ItemId=24)
   SaleItems(25)=(WeaponDef=Class'KFGame.KFWeapDef_Deagle',ClassName="KFWeap_Pistol_Deagle",DualClassName="KFWeap_Pistol_DualDeagle",AssociatedPerkClasses=(Class'KFGame.KFPerk_Gunslinger'),MaxSpareAmmo=105,SecondaryAmmoImagePath="UI_SecondaryAmmo_TEX.GasTank",GroupPriority=25.000000,WeaponStats=((StatValue=91.000000),(StatType=TWS_Penetration,StatValue=2.000000),(StatType=TWS_Range,StatValue=50.000000),(StatType=TWS_RateOfFire,StatValue=300.000000)),InitialSpareMags=5,MagazineCapacity=7,BlocksRequired=2,InventoryGroup=1,ItemId=25)
   SaleItems(26)=(WeaponDef=Class'KFGame.KFWeapDef_DeagleDual',ClassName="KFWeap_Pistol_DualDeagle",SingleClassName="KFWeap_Pistol_Deagle",AssociatedPerkClasses=(Class'KFGame.KFPerk_Gunslinger'),MaxSpareAmmo=98,SecondaryAmmoImagePath="UI_SecondaryAmmo_TEX.GasTank",GroupPriority=45.000000,WeaponStats=((StatValue=91.000000),(StatType=TWS_Penetration,StatValue=2.000000),(StatType=TWS_Range,StatValue=50.000000),(StatType=TWS_RateOfFire,StatValue=545.454529)),InitialSpareMags=2,MagazineCapacity=14,BlocksRequired=4,ItemId=26)
   SaleItems(27)=(WeaponDef=Class'KFGame.KFWeapDef_SW500',ClassName="KFWeap_Revolver_SW500",DualClassName="KFWeap_Revolver_DualSW500",AssociatedPerkClasses=(Class'KFGame.KFPerk_Gunslinger',Class'KFGame.KFPerk_Sharpshooter'),MaxSpareAmmo=100,SecondaryAmmoImagePath="UI_SecondaryAmmo_TEX.GasTank",GroupPriority=30.000000,WeaponStats=((StatValue=150.000000),(StatType=TWS_Penetration,StatValue=3.000000),(StatType=TWS_Range,StatValue=50.000000),(StatType=TWS_RateOfFire,StatValue=250.000000)),InitialSpareMags=5,MagazineCapacity=5,BlocksRequired=3,InventoryGroup=1,ItemId=27)
   SaleItems(28)=(WeaponDef=Class'KFGame.KFWeapDef_SW500Dual',ClassName="KFWeap_Revolver_DualSW500",SingleClassName="KFWeap_Revolver_SW500",AssociatedPerkClasses=(Class'KFGame.KFPerk_Gunslinger'),MaxSpareAmmo=95,SecondaryAmmoImagePath="UI_SecondaryAmmo_TEX.GasTank",GroupPriority=50.000000,WeaponStats=((StatValue=150.000000),(StatType=TWS_Penetration,StatValue=3.000000),(StatType=TWS_Range,StatValue=50.000000),(StatType=TWS_RateOfFire,StatValue=315.789490)),InitialSpareMags=2,MagazineCapacity=10,BlocksRequired=6,ItemId=28)
   SaleItems(29)=(WeaponDef=Class'KFGame.KFWeapDef_MB500',ClassName="KFWeap_Shotgun_MB500",AssociatedPerkClasses=(Class'KFGame.KFPerk_Support'),MaxSpareAmmo=56,SecondaryAmmoImagePath="UI_SecondaryAmmo_TEX.GasTank",GroupPriority=25.000000,WeaponStats=((StatValue=140.000000),(StatType=TWS_Penetration,StatValue=2.000000),(StatType=TWS_Range,StatValue=20.000000),(StatType=TWS_RateOfFire,StatValue=77.922081)),InitialSpareMags=3,MagazineCapacity=8,BlocksRequired=5,TraderFilter=FT_Shotgun,ItemId=29)
   SaleItems(30)=(WeaponDef=Class'KFGame.KFWeapDef_DoubleBarrel',ClassName="KFWeap_Shotgun_DoubleBarrel",AssociatedPerkClasses=(Class'KFGame.KFPerk_Support'),MaxSpareAmmo=46,SecondaryAmmoImagePath="UI_SecondaryAmmo_TEX.GasTank",GroupPriority=50.000000,WeaponStats=((StatValue=300.000000),(StatType=TWS_Penetration,StatValue=2.000000),(StatType=TWS_Range,StatValue=15.000000),(StatType=TWS_RateOfFire,StatValue=240.000000)),InitialSpareMags=11,MagazineCapacity=2,BlocksRequired=4,TraderFilter=FT_Shotgun,ItemId=30)
   SaleItems(31)=(WeaponDef=Class'KFGame.KFWeapDef_HZ12',ClassName="KFWeap_Shotgun_HZ12",AssociatedPerkClasses=(Class'KFGame.KFPerk_Support'),MaxSpareAmmo=80,SecondaryAmmoImagePath="UI_SecondaryAmmo_TEX.GasTank",GroupPriority=55.000000,WeaponStats=((StatValue=200.000000),(StatType=TWS_Penetration,StatValue=2.000000),(StatType=TWS_Range,StatValue=20.000000),(StatType=TWS_RateOfFire,StatValue=600.000000)),InitialSpareMags=1,MagazineCapacity=16,BlocksRequired=5,TraderFilter=FT_Shotgun,ItemId=31)
   SaleItems(32)=(WeaponDef=Class'KFGame.KFWeapDef_M4',ClassName="KFWeap_Shotgun_M4",AssociatedPerkClasses=(Class'KFGame.KFPerk_Support'),MaxSpareAmmo=64,SecondaryAmmoImagePath="UI_SecondaryAmmo_TEX.GasTank",GroupPriority=75.000000,WeaponStats=((StatValue=210.000000),(StatType=TWS_Penetration,StatValue=2.000000),(StatType=TWS_Range,StatValue=35.000000),(StatType=TWS_RateOfFire,StatValue=266.666687)),InitialSpareMags=3,MagazineCapacity=8,BlocksRequired=7,TraderFilter=FT_Shotgun,ItemId=32)
   SaleItems(33)=(WeaponDef=Class'KFGame.KFWeapDef_AA12',ClassName="KFWeap_Shotgun_AA12",AssociatedPerkClasses=(Class'KFGame.KFPerk_Support'),MaxSpareAmmo=120,SecondaryAmmoImagePath="UI_SecondaryAmmo_TEX.GasTank",GroupPriority=100.000000,WeaponStats=((StatValue=140.000000),(StatType=TWS_Penetration,StatValue=2.000000),(StatType=TWS_Range,StatValue=30.000000),(StatType=TWS_RateOfFire,StatValue=300.000000)),InitialSpareMags=1,MagazineCapacity=20,BlocksRequired=10,TraderFilter=FT_Shotgun,ItemId=33)
   SaleItems(34)=(WeaponDef=Class'KFGame.KFWeapDef_CaulkBurn',ClassName="KFWeap_Flame_CaulkBurn",AssociatedPerkClasses=(Class'KFGame.KFPerk_Firebug'),MaxSpareAmmo=500,SecondaryAmmoImagePath="UI_SecondaryAmmo_TEX.GasTank",GroupPriority=25.000000,WeaponStats=((StatValue=70.400002),(StatType=TWS_Penetration),(StatType=TWS_Range,StatValue=15.000000),(StatType=TWS_RateOfFire,StatValue=857.142883)),InitialSpareMags=5,MagazineCapacity=50,BlocksRequired=5,TraderFilter=FT_Flame,ItemId=34)
   SaleItems(35)=(WeaponDef=Class'KFGame.KFWeapDef_FlareGun',ClassName="KFWeap_Pistol_Flare",DualClassName="KFWeap_Pistol_DualFlare",AssociatedPerkClasses=(Class'KFGame.KFPerk_Firebug',Class'KFGame.KFPerk_Gunslinger',Class'KFGame.KFPerk_Sharpshooter'),MaxSpareAmmo=186,SecondaryAmmoImagePath="UI_SecondaryAmmo_TEX.GasTank",GroupPriority=15.000000,WeaponStats=((StatValue=40.000000),(StatType=TWS_Penetration),(StatType=TWS_Range,StatValue=50.000000),(StatType=TWS_RateOfFire,StatValue=300.000000)),InitialSpareMags=15,MagazineCapacity=6,BlocksRequired=2,AltTraderFilter=FT_Flame,InventoryGroup=1,ItemId=35)
   SaleItems(36)=(WeaponDef=Class'KFGame.KFWeapDef_FlareGunDual',ClassName="KFWeap_Pistol_DualFlare",SingleClassName="KFWeap_Pistol_Flare",AssociatedPerkClasses=(Class'KFGame.KFPerk_Firebug',Class'KFGame.KFPerk_Gunslinger'),MaxSpareAmmo=180,SecondaryAmmoImagePath="UI_SecondaryAmmo_TEX.GasTank",GroupPriority=35.000000,WeaponStats=((StatValue=40.000000),(StatType=TWS_Penetration),(StatType=TWS_Range,StatValue=50.000000),(StatType=TWS_RateOfFire,StatValue=545.454529)),InitialSpareMags=7,MagazineCapacity=12,BlocksRequired=4,AltTraderFilter=FT_Flame,ItemId=36)
   SaleItems(37)=(WeaponDef=Class'KFGame.KFWeapDef_DragonsBreath',ClassName="KFWeap_Shotgun_DragonsBreath",AssociatedPerkClasses=(Class'KFGame.KFPerk_Firebug',Class'KFGame.KFPerk_Support'),MaxSpareAmmo=57,SecondaryAmmoImagePath="UI_SecondaryAmmo_TEX.GasTank",GroupPriority=50.000000,WeaponStats=((StatValue=243.000000),(StatType=TWS_Penetration,StatValue=2.000000),(StatType=TWS_Range,StatValue=25.000000),(StatType=TWS_RateOfFire,StatValue=86.956520)),InitialSpareMags=4,MagazineCapacity=6,BlocksRequired=5,TraderFilter=FT_Shotgun,AltTraderFilter=FT_Flame,ItemId=37)
   SaleItems(38)=(WeaponDef=Class'KFGame.KFWeapDef_FlameThrower',ClassName="KFWeap_Flame_Flamethrower",AssociatedPerkClasses=(Class'KFGame.KFPerk_Firebug'),MaxSpareAmmo=500,SecondaryAmmoImagePath="UI_SecondaryAmmo_TEX.GasTank",GroupPriority=75.000000,WeaponStats=((StatValue=96.720009),(StatType=TWS_Penetration),(StatType=TWS_Range,StatValue=17.000000),(StatType=TWS_RateOfFire,StatValue=857.142883)),InitialSpareMags=1,MagazineCapacity=100,BlocksRequired=8,TraderFilter=FT_Flame,ItemId=38)
   SaleItems(39)=(WeaponDef=Class'KFGame.KFWeapDef_MicrowaveGun',ClassName="KFWeap_Beam_Microwave",AssociatedPerkClasses=(Class'KFGame.KFPerk_Firebug'),MaxSpareAmmo=500,SecondaryAmmoImagePath="UI_SecondaryAmmo_TEX.GasTank",GroupPriority=100.000000,WeaponStats=((StatValue=74.400002),(StatType=TWS_Penetration),(StatType=TWS_Range,StatValue=12.000000),(StatType=TWS_RateOfFire,StatValue=857.142883)),MagazineCapacity=100,BlocksRequired=10,TraderFilter=FT_Electric,ItemId=39)
   SaleItems(40)=(WeaponDef=Class'KFGame.KFWeapDef_Winchester1894',ClassName="KFWeap_Rifle_Winchester1894",AssociatedPerkClasses=(Class'KFGame.KFPerk_Sharpshooter',Class'KFGame.KFPerk_Gunslinger'),MaxSpareAmmo=84,SecondaryAmmoImagePath="UI_SecondaryAmmo_TEX.GasTank",GroupPriority=25.000000,WeaponStats=((StatValue=80.000000),(StatType=TWS_Penetration,StatValue=1.500000),(StatType=TWS_Range,StatValue=70.000000),(StatType=TWS_RateOfFire,StatValue=150.000000)),InitialSpareMags=4,MagazineCapacity=12,BlocksRequired=5,TraderFilter=FT_Rifle,ItemId=40)
   SaleItems(41)=(WeaponDef=Class'KFGame.KFWeapDef_CenterfireMB464',ClassName="KFWeap_Rifle_CenterfireMB464",AssociatedPerkClasses=(Class'KFGame.KFPerk_Sharpshooter',Class'KFGame.KFPerk_Gunslinger'),MaxSpareAmmo=70,SecondaryAmmoImagePath="UI_SecondaryAmmo_TEX.GasTank",GroupPriority=50.000000,WeaponStats=((StatValue=180.000000),(StatType=TWS_Penetration,StatValue=1.500000),(StatType=TWS_Range,StatValue=70.000000),(StatType=TWS_RateOfFire,StatValue=150.000000)),InitialSpareMags=2,MagazineCapacity=10,BlocksRequired=5,TraderFilter=FT_Rifle,ItemId=41)
   SaleItems(42)=(WeaponDef=Class'KFGame.KFWeapDef_Crossbow',ClassName="KFWeap_Bow_Crossbow",AssociatedPerkClasses=(Class'KFGame.KFPerk_Sharpshooter'),MaxSpareAmmo=34,SecondaryAmmoImagePath="UI_SecondaryAmmo_TEX.GasTank",GroupPriority=50.000000,WeaponStats=((StatValue=350.000000),(StatType=TWS_Penetration,StatValue=4.000000),(StatType=TWS_Range,StatValue=80.000000),(StatType=TWS_RateOfFire,StatValue=199.999985)),InitialSpareMags=13,MagazineCapacity=1,BlocksRequired=6,TraderFilter=FT_Projectile,ItemId=42)
   SaleItems(43)=(WeaponDef=Class'KFGame.KFWeapDef_M14EBR',ClassName="KFWeap_Rifle_M14EBR",AssociatedPerkClasses=(Class'KFGame.KFPerk_Sharpshooter'),MaxSpareAmmo=120,SecondaryAmmoImagePath="UI_SecondaryAmmo_TEX.GasTank",GroupPriority=75.000000,WeaponStats=((StatValue=90.000000),(StatType=TWS_Penetration,StatValue=2.000000),(StatType=TWS_Range,StatValue=90.000000),(StatType=TWS_RateOfFire,StatValue=272.727264)),InitialSpareMags=2,MagazineCapacity=20,BlocksRequired=7,TraderFilter=FT_Rifle,ItemId=43)
   SaleItems(44)=(WeaponDef=Class'KFGame.KFWeapDef_RailGun',ClassName="KFWeap_Rifle_RailGun",AssociatedPerkClasses=(Class'KFGame.KFPerk_Sharpshooter'),MaxSpareAmmo=20,SecondaryAmmoImagePath="UI_SecondaryAmmo_TEX.GasTank",GroupPriority=100.000000,WeaponStats=((StatValue=375.000000),(StatType=TWS_Penetration,StatValue=10.000000),(StatType=TWS_Range,StatValue=100.000000),(StatType=TWS_RateOfFire,StatValue=600.000000)),InitialSpareMags=6,MagazineCapacity=1,BlocksRequired=10,TraderFilter=FT_Rifle,ItemId=44)
   SaleItems(45)=(WeaponDef=Class'KFGame.KFWeapDef_9mm',ClassName="KFWeap_Pistol_9mm",DualClassName="KFWeap_Pistol_Dual9mm",AssociatedPerkClasses=(None),MaxSpareAmmo=225,SecondaryAmmoImagePath="UI_SecondaryAmmo_TEX.GasTank",GroupPriority=10.000000,WeaponStats=((StatValue=15.000000),(StatType=TWS_Penetration),(StatType=TWS_Range,StatValue=50.000000),(StatType=TWS_RateOfFire,StatValue=342.857147)),InitialSpareMags=7,MagazineCapacity=15,InventoryGroup=1,ItemId=45)
   SaleItems(46)=(WeaponDef=Class'KFGame.KFWeapDef_9mmDual',ClassName="KFWeap_Pistol_Dual9mm",SingleClassName="KFWeap_Pistol_9mm",AssociatedPerkClasses=(None),MaxSpareAmmo=210,SecondaryAmmoImagePath="UI_SecondaryAmmo_TEX.GasTank",GroupPriority=20.000000,WeaponStats=((StatValue=15.000000),(StatType=TWS_Penetration),(StatType=TWS_Range,StatValue=50.000000),(StatType=TWS_RateOfFire,StatValue=600.000000)),InitialSpareMags=3,MagazineCapacity=30,BlocksRequired=2,InventoryGroup=1,ItemId=46)
   SaleItems(47)=(WeaponDef=Class'KFGame.KFWeapDef_MP7',ClassName="KFWeap_SMG_MP7",AssociatedPerkClasses=(Class'KFGame.KFPerk_SWAT'),MaxSpareAmmo=330,SecondaryAmmoImagePath="UI_SecondaryAmmo_TEX.GasTank",GroupPriority=50.000000,WeaponStats=((StatValue=16.000000),(StatType=TWS_Penetration),(StatType=TWS_Range,StatValue=70.000000),(StatType=TWS_RateOfFire,StatValue=952.380920)),InitialSpareMags=6,MagazineCapacity=30,BlocksRequired=4,TraderFilter=FT_SMG,ItemId=47)
   SaleItems(48)=(WeaponDef=Class'KFGame.KFWeapDef_M16M203',ClassName="KFWeap_AssaultRifle_M16M203",AssociatedPerkClasses=(Class'KFGame.KFPerk_Demolitionist',Class'KFGame.KFPerk_Commando'),MaxSpareAmmo=270,SecondaryAmmoImagePath="ui_firemodes_tex.UI_FireModeSelect_Grenade",GroupPriority=50.000000,WeaponStats=((StatValue=30.000000),(StatType=TWS_Penetration),(StatType=TWS_Range,StatValue=68.000000),(StatType=TWS_RateOfFire,StatValue=697.674377)),InitialSpareMags=3,MagazineCapacity=30,BlocksRequired=6,InitialSecondaryAmmo=4,MaxSecondaryAmmo=14,TraderFilter=FT_Assault,AltTraderFilter=FT_Explosive,ItemId=48)
   SaleItems(49)=(WeaponDef=Class'KFGame.KFWeapDef_MP5RAS',ClassName="KFWeap_SMG_MP5RAS",AssociatedPerkClasses=(Class'KFGame.KFPerk_SWAT'),MaxSpareAmmo=320,SecondaryAmmoImagePath="UI_SecondaryAmmo_TEX.GasTank",GroupPriority=60.000000,WeaponStats=((StatValue=25.000000),(StatType=TWS_Penetration),(StatType=TWS_Range,StatValue=70.000000),(StatType=TWS_RateOfFire,StatValue=895.522339)),InitialSpareMags=4,MagazineCapacity=40,BlocksRequired=4,TraderFilter=FT_SMG,ItemId=49)
   SaleItems(50)=(WeaponDef=Class'KFGame.KFWeapDef_P90',ClassName="KFWeap_SMG_P90",AssociatedPerkClasses=(Class'KFGame.KFPerk_SWAT'),MaxSpareAmmo=350,SecondaryAmmoImagePath="UI_SecondaryAmmo_TEX.GasTank",GroupPriority=80.000000,WeaponStats=((StatValue=30.000000),(StatType=TWS_Penetration),(StatType=TWS_Range,StatValue=70.000000),(StatType=TWS_RateOfFire,StatValue=857.142883)),InitialSpareMags=2,MagazineCapacity=50,BlocksRequired=5,TraderFilter=FT_SMG,ItemId=50)
   SaleItems(51)=(WeaponDef=Class'KFGame.KFWeapDef_Kriss',ClassName="KFWeap_SMG_Kriss",AssociatedPerkClasses=(Class'KFGame.KFPerk_SWAT'),MaxSpareAmmo=495,SecondaryAmmoImagePath="UI_SecondaryAmmo_TEX.GasTank",GroupPriority=100.000000,WeaponStats=((StatValue=33.000000),(StatType=TWS_Penetration),(StatType=TWS_Range,StatValue=70.000000),(StatType=TWS_RateOfFire,StatValue=1200.000000)),InitialSpareMags=4,MagazineCapacity=33,BlocksRequired=6,TraderFilter=FT_SMG,ItemId=51)
   SaleItems(52)=(WeaponDef=Class'KFGame.KFWeapDef_FreezeThrower',ClassName="KFWeap_Ice_FreezeThrower",AssociatedPerkClasses=(Class'KFGame.KFPerk_Survivalist'),MaxSpareAmmo=400,SecondaryAmmoImagePath="UI_SecondaryAmmo_TEX.GasTank",GroupPriority=75.000000,WeaponStats=(,(StatType=TWS_Penetration),(StatType=TWS_Range,StatValue=17.000000),(StatType=TWS_RateOfFire,StatValue=857.142883)),InitialSpareMags=1,MagazineCapacity=100,BlocksRequired=8,TraderFilter=FT_Electric,ItemId=52)
   SaleItems(53)=(WeaponDef=Class'KFGame.KFWeapDef_Hemogoblin',ClassName="KFWeap_Rifle_Hemogoblin",AssociatedPerkClasses=(Class'KFGame.KFPerk_FieldMedic'),MaxSpareAmmo=77,SecondaryAmmoImagePath="UI_SecondaryAmmo_TEX.MedicDarts",GroupPriority=75.000000,WeaponStats=((StatValue=175.000000),(StatType=TWS_Penetration),(StatType=TWS_Range,StatValue=90.000000),(StatType=TWS_RateOfFire,StatValue=240.000000),(StatType=TWS_HealAmount,StatValue=20.000000),(StatType=TWS_RechargeTime,StatValue=15.000000)),InitialSpareMags=3,MagazineCapacity=7,BlocksRequired=8,InitialSecondaryAmmo=100,MaxSecondaryAmmo=100,TraderFilter=FT_Rifle,ItemId=53)
   SaleItems(54)=(WeaponDef=Class'KFGame.KFWeapDef_HK_UMP',ClassName="KFWeap_SMG_HK_UMP",AssociatedPerkClasses=(Class'KFGame.KFPerk_SWAT'),MaxSpareAmmo=290,SecondaryAmmoImagePath="UI_SecondaryAmmo_TEX.GasTank",GroupPriority=90.000000,WeaponStats=((StatValue=45.000000),(StatType=TWS_Penetration),(StatType=TWS_Range,StatValue=70.000000),(StatType=TWS_RateOfFire,StatValue=600.000000)),InitialSpareMags=2,MagazineCapacity=30,BlocksRequired=5,TraderFilter=FT_SMG,ItemId=54)
   
   // New LEENK's weapon
   SaleItems(55)=(WeaponDef=Class'WeaponPack.KFWeapDef_SVD',ClassName="KFWeap_Rifle_SVD",AssociatedPerkClasses=(Class'KFGame.KFPerk_Sharpshooter'),MaxSpareAmmo=100,SecondaryAmmoImagePath="UI_SecondaryAmmo_TEX.GasTank",GroupPriority=90,WeaponStats=((StatValue=350),(StatType=TWS_Penetration),(StatType=TWS_Range,StatValue=160),(StatType=TWS_RateOfFire,StatValue=152.2842639)),InitialSpareMags=3,MagazineCapacity=10,BlocksRequired=8,TraderFilter=FT_Rifle,ItemId=55)
   SaleItems(56)=(WeaponDef=Class'WeaponPack.KFWeapDef_M60MG',ClassName="KFWeap_M60MG",AssociatedPerkClasses=(Class'KFGame.KFPerk_Commando'),MaxSpareAmmo=600,SecondaryAmmoImagePath="UI_SecondaryAmmo_TEX.GasTank",GroupPriority=170,WeaponStats=((StatValue=60),(StatType=TWS_Penetration),(StatType=TWS_Range,StatValue=120),(StatType=TWS_RateOfFire,StatValue=900)),InitialSpareMags=3,MagazineCapacity=100,BlocksRequired=10,TraderFilter=FT_Assault,ItemId=56)
   SaleItems(57)=(WeaponDef=Class'WeaponPack.KFWeapDef_AUG9mm',ClassName="KFWeap_SMG_AUG9mm",AssociatedPerkClasses=(Class'KFGame.KFPerk_SWAT'),MaxSpareAmmo=320,SecondaryAmmoImagePath="UI_SecondaryAmmo_TEX.GasTank",GroupPriority=120,WeaponStats=((StatValue=45),(StatType=TWS_Penetration),(StatType=TWS_Range,StatValue=80),(StatType=TWS_RateOfFire,StatValue=660)),InitialSpareMags=4,MagazineCapacity=40,BlocksRequired=6,TraderFilter=FT_SMG,ItemId=57)
   SaleItems(58)=(WeaponDef=Class'WeaponPack.KFWeapDef_Spas12',ClassName="KFWeap_Shotgun_Spas12",AssociatedPerkClasses=(Class'KFGame.KFPerk_Support'),MaxSpareAmmo=160,SecondaryAmmoImagePath="UI_SecondaryAmmo_TEX.GasTank",GroupPriority=80,WeaponStats=((StatValue=280),(StatType=TWS_Penetration,StatValue=2.7),(StatType=TWS_Range,StatValue=30),(StatType=TWS_RateOfFire,StatValue=150)),InitialSpareMags=5,MagazineCapacity=8,BlocksRequired=6,TraderFilter=FT_Shotgun,ItemId=58)  
   SaleItems(59)=(WeaponDef=Class'WeaponPack.KFWeapDef_Patriot',ClassName="KFWeap_Revolver_Patriot",DualClassName="KFWeap_Revolver_DualPatriot",AssociatedPerkClasses=(Class'KFGame.KFPerk_Demolitionist'),MaxSpareAmmo=102,SecondaryAmmoImagePath="UI_SecondaryAmmo_TEX.GasTank",GroupPriority=55,WeaponStats=((StatValue=130),(StatType=TWS_Penetration),(StatType=TWS_Range,StatValue=130),(StatType=TWS_RateOfFire,StatValue=300)),InitialSpareMags=4,MagazineCapacity=6,BlocksRequired=2,InventoryGroup=1,TraderFilter=FT_Pistol,ItemId=59)
   SaleItems(60)=(WeaponDef=Class'WeaponPack.KFWeapDef_DualPatriot',ClassName="KFWeap_Revolver_DualPatriot",SingleClassName="KFWeap_Revolver_Patriot",AssociatedPerkClasses=(Class'KFGame.KFPerk_Demolitionist'),MaxSpareAmmo=96,SecondaryAmmoImagePath="UI_SecondaryAmmo_TEX.GasTank",GroupPriority=60,WeaponStats=((StatValue=130),(StatType=TWS_Penetration),(StatType=TWS_Range,StatValue=130),(StatType=TWS_RateOfFire,StatValue=600)),InitialSpareMags=3,MagazineCapacity=12,BlocksRequired=4,TraderFilter=FT_Pistol,ItemId=60)
   SaleItems(61)=(WeaponDef=Class'WeaponPack.KFWeapDef_DragonBlade',ClassName="KFWeap_DragonBlade",AssociatedPerkClasses=(Class'KFGame.KFPerk_Berserker'),SecondaryAmmoImagePath="UI_SecondaryAmmo_TEX.GasTank",GroupPriority=110,WeaponStats=((StatValue=220),(StatType=TWS_Penetration),(StatType=TWS_Range,StatValue=15),(StatType=TWS_RateOfFire,StatValue=100),(StatType=TWS_Block,StatValue=0.5),(StatType=TWS_Parry,StatValue=0.7)),BlocksRequired=7,TraderFilter=FT_Melee,InventoryGroup=2,ItemId=61)
   SaleItems(62)=(WeaponDef=Class'WeaponPack.KFWeapDef_Glock',ClassName="KFWeap_Pistol_Glock",DualClassName="KFWeap_Pistol_DualGlock",AssociatedPerkClasses=(Class'KFGame.KFPerk_Gunslinger'),MaxSpareAmmo=627,SecondaryAmmoImagePath="UI_SecondaryAmmo_TEX.GasTank",GroupPriority=22,WeaponStats=((StatValue=30),(StatType=TWS_Penetration),(StatType=TWS_Range,StatValue=50),(StatType=TWS_RateOfFire,StatValue=1200)),InitialSpareMags=9,MagazineCapacity=33,BlocksRequired=2,InventoryGroup=1,TraderFilter=FT_Pistol,ItemId=62)
   SaleItems(63)=(WeaponDef=Class'WeaponPack.KFWeapDef_GlockDual',ClassName="KFWeap_Pistol_DualGlock",SingleClassName="WeaponPack.KFWeap_Pistol_Glock",AssociatedPerkClasses=(Class'KFGame.KFPerk_Gunslinger'),MaxSpareAmmo=594,SecondaryAmmoImagePath="UI_SecondaryAmmo_TEX.GasTank",GroupPriority=44,WeaponStats=((StatValue=30),(StatType=TWS_Penetration),(StatType=TWS_Range,StatValue=50),(StatType=TWS_RateOfFire,StatValue=2400)),InitialSpareMags=4,MagazineCapacity=66,BlocksRequired=4,TraderFilter=FT_Pistol,ItemId=63)
   SaleItems(64)=(WeaponDef=Class'WeaponPack.KFWeapDef_Skull9',ClassName="KFWeap_Skull9",AssociatedPerkClasses=(Class'KFGame.KFPerk_Berserker'),SecondaryAmmoImagePath="UI_SecondaryAmmo_TEX.GasTank",GroupPriority=130,WeaponStats=((StatValue=900),(StatType=TWS_Penetration),(StatType=TWS_Range,StatValue=20),(StatType=TWS_RateOfFire,StatValue=100),(StatType=TWS_Block,StatValue=0.7),(StatType=TWS_Parry,StatValue=0.9)),BlocksRequired=10,TraderFilter=FT_Melee,InventoryGroup=2,ItemId=64)
   SaleItems(65)=(WeaponDef=Class'WeaponPack.KFWeapDef_H134',ClassName="KFWeap_Medic_H134",AssociatedPerkClasses=(Class'KFGame.KFPerk_FieldMedic',Class'KFGame.KFPerk_Support'),MaxSpareAmmo=300,SecondaryAmmoImagePath="UI_SecondaryAmmo_TEX.MedicDarts",GroupPriority=110,WeaponStats=((StatValue=300),(StatType=TWS_Penetration,StatValue=3.5),(StatType=TWS_Range,StatValue=90),(StatType=TWS_RateOfFire,StatValue=300),(StatType=TWS_HealAmount,StatValue=20),(StatType=TWS_RechargeTime,StatValue=15)),InitialSpareMags=3,MagazineCapacity=60,BlocksRequired=8,InitialSecondaryAmmo=200,MaxSecondaryAmmo=200,TraderFilter=FT_Shotgun,ItemId=65)
   SaleItems(66)=(WeaponDef=Class'WeaponPack.KFWeapDef_Healthpack',ClassName="KFWeap_Healthpack",AssociatedPerkClasses=(Class'KFGame.KFPerk_FieldMedic'),MaxSpareAmmo=30,SecondaryAmmoImagePath="UI_SecondaryAmmo_TEX.MedicDarts",GroupPriority=21,WeaponStats=((StatValue=0),(StatType=TWS_Penetration),(StatType=TWS_Range,StatValue=0),(StatType=TWS_RateOfFire,StatValue=240.000000)),InitialSpareMags=5,MagazineCapacity=1,BlocksRequired=2,TraderFilter=FT_Explosive,ItemId=66)
   SaleItems(67)=(WeaponDef=Class'WeaponPack.KFWeapDef_AmmoBox',ClassName="KFWeap_AmmoBox",AssociatedPerkClasses=(Class'KFGame.KFPerk_Support'),MaxSpareAmmo=50,SecondaryAmmoImagePath="UI_SecondaryAmmo_TEX.MedicDarts",GroupPriority=21,WeaponStats=((StatValue=0),(StatType=TWS_Penetration),(StatType=TWS_Range,StatValue=0),(StatType=TWS_RateOfFire,StatValue=0)),InitialSpareMags=10,MagazineCapacity=1,BlocksRequired=3,TraderFilter=FT_Explosive,ItemId=67)
   SaleItems(68)=(WeaponDef=Class'WeaponPack.KFWeapDef_Seeker3K',ClassName="KFWeap_RocketLauncher_Seeker3K",AssociatedPerkClasses=(Class'KFGame.KFPerk_Demolitionist'),MaxSpareAmmo=144,SecondaryAmmoImagePath="UI_SecondaryAmmo_TEX.GasTank",GroupPriority=120.000000,WeaponStats=((StatValue=250.000000),(StatType=TWS_Penetration),(StatType=TWS_Range,StatValue=100.000000),(StatType=TWS_RateOfFire,StatValue=171.428574)),InitialSpareMags=3,MagazineCapacity=18,BlocksRequired=9,TraderFilter=FT_Explosive,ItemId=68)
   SaleItems(69)=(WeaponDef=Class'WeaponPack.KFWeapDef_M14EBRAR',ClassName="KFWeap_AssaultRifle_M14EBR",AssociatedPerkClasses=(Class'KFGame.KFPerk_Commando'),MaxSpareAmmo=240,SecondaryAmmoImagePath="UI_SecondaryAmmo_TEX.GasTank",GroupPriority=110.000000,WeaponStats=((StatValue=90.000000),(StatType=TWS_Penetration,StatValue=90),(StatType=TWS_Range,StatValue=90),(StatType=TWS_RateOfFire,StatValue=750)),InitialSpareMags=3,MagazineCapacity=30,BlocksRequired=7,TraderFilter=FT_Assault,ItemId=69)
   SaleItems(70)=(WeaponDef=Class'WeaponPack.KFWeapDef_M16Medic',ClassName="KFWeap_AssaultRifle_M16Medic",AssociatedPerkClasses=(Class'KFGame.KFPerk_FieldMedic'),MaxSpareAmmo=350,SecondaryAmmoImagePath="ui_firemodes_tex.UI_FireModeSelect_Grenade",GroupPriority=70,WeaponStats=((StatValue=38.000000),(StatType=TWS_Penetration),(StatType=TWS_Range,StatValue=70.000000),(StatType=TWS_RateOfFire,StatValue=650)),InitialSpareMags=3,MagazineCapacity=30,BlocksRequired=6,InitialSecondaryAmmo=5,MaxSecondaryAmmo=40,TraderFilter=FT_Assault,ItemId=70)
   SaleItems(71)=(WeaponDef=Class'WeaponPack.KFWeapDef_AS50',ClassName="KFWeap_Sniper_AS50",AssociatedPerkClasses=(Class'KFGame.KFPerk_Sharpshooter'),MaxSpareAmmo=56,SecondaryAmmoImagePath="UI_SecondaryAmmo_TEX.GasTank",GroupPriority=170,WeaponStats=((StatValue=950.000000),(StatType=TWS_Penetration,StatValue=4.0),(StatType=TWS_Range,StatValue=150.000000),(StatType=TWS_RateOfFire,StatValue=200)),InitialSpareMags=2,MagazineCapacity=7,BlocksRequired=11,TraderFilter=FT_Rifle,ItemID=71)
   SaleItems(72)=(WeaponDef=Class'WeaponPack.KFWeapDef_M10',ClassName="KFWeap_SMG_M10",DualClassName="KFWeap_DualM10",AssociatedPerkClasses=(Class'KFGame.KFPerk_SWAT'),MaxSpareAmmo=270,SecondaryAmmoImagePath="UI_SecondaryAmmo_TEX.GasTank",GroupPriority=90,WeaponStats=((StatValue=28),(StatType=TWS_Penetration),(StatType=TWS_Range,StatValue=70),(StatType=TWS_RateOfFire,StatValue=1380)),InitialSpareMags=3,MagazineCapacity=30,BlocksRequired=3,TraderFilter=FT_SMG,ItemId=72)
   SaleItems(73)=(WeaponDef=Class'WeaponPack.KFWeapDef_DualM10',ClassName="KFWeap_DualM10",SingleClassName="KFWeap_SMG_M10",AssociatedPerkClasses=(Class'KFGame.KFPerk_SWAT'),MaxSpareAmmo=540,SecondaryAmmoImagePath="UI_SecondaryAmmo_TEX.GasTank",GroupPriority=92,WeaponStats=((StatValue=28),(StatType=TWS_Penetration),(StatType=TWS_Range,StatValue=1380),(StatType=TWS_RateOfFire,StatValue=600)),InitialSpareMags=3,MagazineCapacity=60,BlocksRequired=6,TraderFilter=FT_SMG,ItemId=73)
   SaleItems(74)=(WeaponDef=Class'WeaponPack.KFWeapDef_Buzzsaw',ClassName="KFWeap_Buzzsaw",AssociatedPerkClasses=(Class'KFGame.KFPerk_Berserker'),MaxSpareAmmo=45,SecondaryAmmoImagePath="UI_SecondaryAmmo_TEX.GasTank",GroupPriority=110,WeaponStats=((StatValue=550.000000),(StatType=TWS_Penetration,StatValue=6.0),(StatType=TWS_Range,StatValue=200),(StatType=TWS_RateOfFire,StatValue=600)),InitialSpareMags=21,MagazineCapacity=1,BlocksRequired=6,TraderFilter=FT_Projectile,ItemId=74)
   SaleItems(75)=(WeaponDef=Class'WeaponPack.KFWeapDef_Albert',ClassName="KFWeap_Pistol_Albert",DualClassName="KFWeap_Pistol_DualAlbert",AssociatedPerkClasses=(Class'KFGame.KFPerk_Gunslinger'),MaxSpareAmmo=90,SecondaryAmmoImagePath="UI_SecondaryAmmo_TEX.GasTank",GroupPriority=27,WeaponStats=((StatValue=75.000),(StatType=TWS_Penetration,StatValue=2.7),(StatType=TWS_Range,StatValue=50),(StatType=TWS_RateOfFire,StatValue=342)),InitialSpareMags=5,MagazineCapacity=9,BlocksRequired=2,InventoryGroup=1,TraderFilter=FT_Pistol,ItemId=75)
   SaleItems(76)=(WeaponDef=Class'WeaponPack.KFWeapDef_AlbertDual',ClassName="KFWeap_Pistol_DualAlbert",SingleClassName="KFWeap_Pistol_Albert",AssociatedPerkClasses=(Class'KFGame.KFPerk_Gunslinger'),MaxSpareAmmo=180,SecondaryAmmoImagePath="UI_SecondaryAmmo_TEX.GasTank",GroupPriority=58,WeaponStats=((StatValue=30),(StatType=TWS_Penetration,StatValue=2.7),(StatType=TWS_Range,StatValue=50),(StatType=TWS_RateOfFire,StatValue=685)),InitialSpareMags=5,MagazineCapacity=18,BlocksRequired=4,TraderFilter=FT_Pistol,ItemId=76)
   SaleItems(77)=(WeaponDef=Class'WeaponPack.KFWeapDef_Scythe',ClassName="KFWeap_Edged_Scythe",AssociatedPerkClasses=(Class'KFGame.KFPerk_Berserker'),SecondaryAmmoImagePath="UI_SecondaryAmmo_TEX.GasTank",GroupPriority=100,WeaponStats=((StatValue=600),(StatType=TWS_Penetration),(StatType=TWS_Range,StatValue=15),(StatType=TWS_RateOfFire,StatValue=100),(StatType=TWS_Block,StatValue=0.6),(StatType=TWS_Parry,StatValue=0.7)),BlocksRequired=8,TraderFilter=FT_Melee,InventoryGroup=2,ItemId=77)
   //SaleItems(73)
   //SaleItems(73)

   // end
   End Object
   MyTraderItems=KFGFxObject_TraderItems'MyDefaultTraderItems'
